name: saibya_daily
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  dio: ^5.7.0

  shared_preferences: ^2.3.2

  shimmer: ^3.0.0

  intl: ^0.19.0

  flutter_native_splash: ^2.4.2

  fl_chart: ^0.71.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/


  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-VariableFont_wght.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_wght.ttf 

flutter_native_splash:
  color: "#ffffff" 
  image: assets/icon/icon.png
  android: true 
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"


